In [67]:
import numpy as np
import h5py
import torch
import matplotlib.pyplot as plt

In [80]:
data_dir = "/Users/charlieruan/projects_data/McMahon/data/lorenz_training_rk.hdf5"
file_path = "/Users/charlieruan/projects_data/McMahon/data/train_10_pendula.hdf5"
data = None
examples = []
block_size = 16
stride = 16
ndata = 1024

with h5py.File(data_dir, "r") as f:
    # Iterate through stored time-series
    samples = 0
    for key in f.keys():
        data_series = torch.Tensor(f[key])
        # Stride over time-series
        for i in range(0,  data_series.size(0) - block_size + 1, stride):  # Truncate in block of block_size
            examples.append(data_series[i : i + block_size].unsqueeze(0))

        samples = samples + 1
        if(ndata > 0 and samples > ndata): #If we have enough time-series samples break loop
            break

In [93]:
examples = []
cur_num = 0
with h5py.File(file_path, "r") as f:
    for key in f.keys():
        data_series = torch.Tensor(np.array(f[key]))
        examples.append(data_series.unsqueeze(0))
        cur_num += 1
        if (cur_num >= ndata):
            break
data = torch.cat(examples, dim=0)
self.mu = torch.mean(data, dim=(0,1)) # mean for each state across data and time
self.std = torch.std(data, dim=(0,1)) # std for each state across data and time

dataset = self.PendulumDataset(data)
training_loader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

NameError: name 'self' is not defined

In [85]:
data.shape

torch.Size([1024, 60, 20])

In [88]:
torch.mean(data[:,:,0])

tensor(0.0014)

In [92]:
torch.mean(data, dim=(0,1))

tensor([ 1.4264e-03, -2.7336e-02,  9.9022e-04,  1.7065e-02, -1.3073e-03,
        -3.3324e-03, -5.3278e-04,  2.4870e-02,  4.6689e-04, -2.5838e-02,
         4.7171e-04,  1.9141e-02, -9.1947e-05, -2.1275e-02, -1.0221e-03,
         1.1455e-02, -1.9095e-03, -1.4080e-02, -3.7234e-04,  1.4630e-02])

In [96]:
torch.linspace(1, 0, 32)

tensor([1.0000, 0.9677, 0.9355, 0.9032, 0.8710, 0.8387, 0.8065, 0.7742, 0.7419,
        0.7097, 0.6774, 0.6452, 0.6129, 0.5806, 0.5484, 0.5161, 0.4839, 0.4516,
        0.4194, 0.3871, 0.3548, 0.3226, 0.2903, 0.2581, 0.2258, 0.1935, 0.1613,
        0.1290, 0.0968, 0.0645, 0.0323, 0.0000])

In [97]:
n_embd = 32
xidx = []
yidx = []
for i in range(1, 3):
    yidx.append(np.arange(i, n_embd))
    xidx.append(np.arange(0, n_embd-i))

In [98]:
xidx

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])]

In [100]:
yidx

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])]

In [99]:
torch.LongTensor(np.concatenate(xidx))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,  0,  1,  2,  3,  4,
         5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23, 24, 25, 26, 27, 28, 29])